apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secrets
  namespace: flag-service
type: Opaque
stringData:
  POSTGRES_USER: "postgres"  
  POSTGRES_PASSWORD: "postgres"
  MASTER_KEY: "admin-secreto-123"
  DATABASE_URL: "postgres://postgres:postgres@postgres-flags-db.cyvo4suykdq6.us-east-1.rds.amazonaws.com:5432/flags_db"